language: node_js
node_js:
- 12
script:
- yarn build
- printf 'dsp.metodiev.dev' > dist/CNAME
- cp 'README.md' dist
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    tags: true
- provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    tags: true
