language: node_js
node_js:
- 12
script:
- yarn build
- printf 'dsp.metodiev.dev' > dist/CNAME
- cp 'README.md' dist
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token:
    secure: E9GLa1Day3IH4l6PdTwpt2oaiuuqO/WsxN9XH/lfJH/swXON4XN4a2Y5aMbjHXlc0DDNbBe+lDj4/DAxGL8edh45v/i6+yLx32KdOXeNhyKU7KH2ghO9TKFe8IeG6RlqFOD/4Hn8hlCfcJEh+u0WEK1oh0YV6nihM8AZj8xKlmPAcZVGErCiInJ+g6E/wlwgL+tEw+RosxqktjYbOoaHT0ZanlL8gkfLaOv0kDtUmJFhrsUW1QoPnStw/ZkS78/Jhutzhqdkcpnr5jBN8/jEQkma4DPlLT4BDZ3uPerOFuha+8EoEt0fBE30wj67s1xFlj5CTBMnMflYQmCc1JLV5ntYQ6LHbPvUALGOnr7VghFHDyt1UwJPNPxOTzrNpO0mZRB6Jc39MrNlmknpTk8FjM7wkpqg4FxlhCkp/f2hjrB1oRRJ3Z01zJPOhUOKeuTdcdSFfGgXR/MocbK0RMo5/WOIi1/Dwj9i6Ee93fS3KkmBUSE7r5c5KITRxUYeQzsA0bCxmhw36qZE1/qQXkWzOC5kPXnH2/pK/+c1GXueR+G+RjNNrllUNrH6kCpgnN+K6FwyuP1t56C/ix5nAJkiIuL/chm2b11MPRUG8Sx9/7qlx5OM6xwYYPnQ9911+R9FLOc1CdReHK6M9GaDExZ8qBmSHYE0DzZpNmKi0TPyUvw=
  on:
    tags: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: E9GLa1Day3IH4l6PdTwpt2oaiuuqO/WsxN9XH/lfJH/swXON4XN4a2Y5aMbjHXlc0DDNbBe+lDj4/DAxGL8edh45v/i6+yLx32KdOXeNhyKU7KH2ghO9TKFe8IeG6RlqFOD/4Hn8hlCfcJEh+u0WEK1oh0YV6nihM8AZj8xKlmPAcZVGErCiInJ+g6E/wlwgL+tEw+RosxqktjYbOoaHT0ZanlL8gkfLaOv0kDtUmJFhrsUW1QoPnStw/ZkS78/Jhutzhqdkcpnr5jBN8/jEQkma4DPlLT4BDZ3uPerOFuha+8EoEt0fBE30wj67s1xFlj5CTBMnMflYQmCc1JLV5ntYQ6LHbPvUALGOnr7VghFHDyt1UwJPNPxOTzrNpO0mZRB6Jc39MrNlmknpTk8FjM7wkpqg4FxlhCkp/f2hjrB1oRRJ3Z01zJPOhUOKeuTdcdSFfGgXR/MocbK0RMo5/WOIi1/Dwj9i6Ee93fS3KkmBUSE7r5c5KITRxUYeQzsA0bCxmhw36qZE1/qQXkWzOC5kPXnH2/pK/+c1GXueR+G+RjNNrllUNrH6kCpgnN+K6FwyuP1t56C/ix5nAJkiIuL/chm2b11MPRUG8Sx9/7qlx5OM6xwYYPnQ9911+R9FLOc1CdReHK6M9GaDExZ8qBmSHYE0DzZpNmKi0TPyUvw=
  on:
    tags: true
